### ISSUE TITLE
FR: Pomodoro timer-like sound notifications indicating timeblock status (working on task, or on break)

### ISSUE THREAD

**Issue by greghab** [ichernyshovvv/org-timeblock#16]
[Pomodoro timers ](https://gitlab.gnome.org/World/Solanum)mainly use 2x sounds:
- 1: a task start sound
- 2: a task stop sound
  - (And a 3: break end sound, but this can be ignored)

It would be cool if 1 and 2 could be triggered automatically based of a timeblocked schedule, so that there is a live feedback loop letting me know what's going on with my schedule and where I'm at within it, without having to regularly glance at the actual schedule itself.

Also it would be cool if sounds could be customized to specific tasks
- (Say notification sounds for exercise, are different than normal work, so I can know what task I'm going into by just listening to the sound itself).

----
And in addition, maybe some sort of [espeak](https://github.com/smoge/say-region.el) or [Emacspeak](https://github.com/tvraman/emacspeak) speaking the task name when entering a new timeblock, to further clarify and exalt what exact timeblock is being entered.

**Comment by ichernyshovvv** [comment]
> It would be cool if 1 and 2 could be triggered automatically based of a timeblocked schedule, so that there is a live feedback loop letting me know what's going on with my schedule and where I'm at within it, without having to regularly glance at the actual schedule itself.

I don't think this feature is somehow related to a package that just provides interactive day-view calendar for orgmode tasks. Instead, this could be implemented as a separate package.

> And in addition, maybe some sort of [espeak](https://github.com/smoge/say-region.el) or [Emacspeak](https://github.com/tvraman/emacspeak) speaking the task name when entering a new timeblock, to further clarify and exalt what exact timeblock is being entered.

Maybe this feature makes sense in org-agenda for a blind person, but definitely not in org-timeblock which is a visual day-view calendar.

**Comment by yantar92** [comment]
greghab ***@***.***> writes:

> - 2: a task stop sound

Just set ~org-clock-sound~ to get this.

-- 
Ihor Radchenko // yantar92,
Org mode contributor,
Learn more about Org mode at <https://orgmode.org/>.
Support Org development at <https://liberapay.com/org-mode>,
or support my work at <https://liberapay.com/yantar92>
