### ISSUE TITLE
unicode support?!

### ISSUE THREAD

**Issue by junghan0611** [ichernyshovvv/org-timeblock#17]
![image](https://github.com/ichernyshovvv/org-timeblock/assets/31724164/d3d6d520-6c26-4bc9-a336-b00f4c89e79a)

Timeblocks doesn's show cjk languege and emoji.

**Comment by artsi0m** [comment]
![image](https://github.com/ichernyshovvv/org-timeblock/assets/87656471/c8e10819-cb69-404f-bacc-678a62a91a6d)


It can display cyrillic characters which is part of unicode and UTF-8.
So, it maybe an issue with the font that you have set in emacs for displaying text in timeblocking buffer.

**Comment by junghan0611** [comment]
> 
> ![image](https://github.com/ichernyshovvv/org-timeblock/assets/87656471/c8e10819-cb69-404f-bacc-678a62a91a6d)
> 
> 
> It can display cyrillic characters which is part of unicode and UTF-8.
> So, it maybe an issue with the font that you have set in emacs for displaying text in timeblocking buffer.

thanks i will try

**Comment by ichernyshovvv** [comment]
If you've solved the issue somehow, share with us. I tried to create org entries with cjk characters and emojies, and got no problems displaying them.

**Comment by junghan0611** [comment]
> If you've solved the issue somehow, share with us. I tried to create org entries with cjk characters and emojies, and got no problems displaying them.

I haven't solved it yet, can you please point me to the part of your code that handles the text, I'm trying to see the SVG conversion part.

**Comment by ichernyshovvv** [comment]
![image](https://github.com/ichernyshovvv/org-timeblock/assets/130583075/4b602580-efbe-4c66-91d0-556e760bd409)

As I said, I have no issues with displaying emojies, cjk, or whatever. 

org-timeblock uses svg.el library. For adding text to a svg image, see `svg-text` function.
