### ISSUE TITLE
Recurring tasks/events are ignored

### ISSUE THREAD

**Issue by real-or-random** [ichernyshovvv/org-timeblock#18]
It's 2023-08-24 today.

This event won't show up in today's timeblock view (but it should!)
```
* Recurring event which started in the past 
<2023-02-20 Mon 12:00-13:00 +1d>
```

This event shows up:
```
* Event today  
<2023-08-24 Mon 12:00-13:00 +1d>
```

**Comment by ichernyshovvv** [comment]
Will be fixed, thank you

**Comment by alphapapa** [comment]
This might be due to a limitation of org-ql (which will be fixed also).

**Comment by ichernyshovvv** [comment]
Hi, @real-or-random. Repeated tasks/events now seem to be displayed as wanted. Check with the newest commit on the master branch and let me know if it works for you.

**Comment by real-or-random** [comment]
Yes, thanks, that fixes it for the common use cases. After looking at https://github.com/ichernyshovvv/org-timeblock/commit/a720989fb902baa0419b52be59b0ba85d6d55653, I tend to think that the approach there is perhaps a bit crude. For example, there could be hourly, monthly, and yearly recurrences, even though daily and weekly are probably by far the most common types. 

I'm not very familiar with org-ql, but I can imagine that the recurrences would ideally be handled by org-ql directly. @alphapapa Is this what you meant above?

**Comment by ichernyshovvv** [comment]
> For example, there could be hourly, monthly, and yearly recurrences, even though daily and weekly are probably by far the most common types

Hourly, mongth, yearly recurrences are also handled and displayed. What do you mean?

**Comment by real-or-random** [comment]
Oh okay, then it's alright! I had not tested it, I only had a glimpse at the commit and saw the `pcase` with `week` and `day`, so I was assuming the code handles only weekly and daily, sorry.

**Comment by ichernyshovvv** [comment]
> I only had a glimpse at the commit and saw the pcase with week and day

pcase is needed to convert weeks to days, because ts-inc does not support `week` slot
