### ISSUE TITLE
UI rendered too small

### ISSUE THREAD

**Issue by aetherspritee** [ichernyshovvv/org-timeblock#22]
Hey there, 
what a great package! ive been wanting such a functionality for a long time.

I installed org-timeblock on Emacs 28.2 using Doom Emacs and the rendered UI is way too small.
Ive tried manually setting the values for `org-timeblock-svg-width` and `org-timeblock-svg-height`, but it seems they are overwritten once the timeblock UI is actually drawn.
Any ideas as to what might cause that problem? Could you maybe allow for users to set the desired size of the UI?
Thanks alot in advance :)

<img width="2560" alt="Screenshot 2023-09-02 at 10 32 20" src="https://github.com/ichernyshovvv/org-timeblock/assets/94076757/d234fa18-b942-4acd-96ee-5abb96f75fd1">

**Comment by ichernyshovvv** [comment]
Hi, thank you

It seems like you have changed the default values of customizable variables in image-mode.el, however I couldn't reproduce your issue. Can you please provide your settings for image-mode? Looks like your image-mode.el displays every image with 50% scale.

**Comment by aetherspritee** [comment]
I have not changed any such variables. I tried playing around with `image-increase-size` and `image-scaling-factor`, but both don't seem to have any effect. 
I have looked into it a bit more, it seems to be a general issue with the svg rendering in homebrew-emacs-plus, which is fixed in version 29.
Thank you!

**Comment by rekahsoft** [comment]
I had display scaling issues on a hidpi monitor with `~/.Xresources~ option `Xft.dpi: 180`. Setting `image-scaling-factor 1` resolves the issue. Thanks for the hints!
