### ISSUE TITLE
Dependency to org-ql

### ISSUE THREAD

**Issue by gan-ainm** [ichernyshovvv/org-timeblock#23]
Today I installed **org-timeblock** on [Crafted Emacs v2beta](https://github.com/SystemCrafters/crafted-emacs/tree/craftedv2beta), which by default uses **package.el**. **org-timeblock**, however, is installed using **package-vc** which caused an error when I tried to evaluate 
``` elisp
(package-vc-install
 '(org-timeblock :url "https://github.com/ichernyshovvv/org-timeblock/"))
```
The message was

```
Compiling file /home/gan/.config/craftedemacs/elpa/org-timeblock/org-timeblock.el at Wed Sep  6 14:23:00 2023
org-timeblock.el:40:2: Error: Cannot open load file: No such file or directory, org-ql
```

A look into the package directories revealed that **org-ql** packages had been downloaded (via package.el) yet not compiled, however, **org-timeblock** was not able to find it.

After manually re-installing **org-ql**, **org-timeblock** compiled

**Comment by ichernyshovvv** [comment]
Hmm, don't know what's the problem here, but have you added melpa archive to `package-archives` list?

`(add-to-list 'package-archives (cons "melpa" "https://melpa.org/packages/") t)`

Also, try to `M-x package-refresh-contents` before trying to install org-timeblock.
