### ISSUE TITLE
BUG: org-timeblock-write saves file with empty background

### ISSUE THREAD

**Issue by artsi0m** [ichernyshovvv/org-timeblock#24]
### Platform
GNU/Emacs 29.1 installed from scoop on windows 10
```

Name        : emacs
Description : An extensible, customizable, free/libre text editor.
Version     : 29.1
Bucket      : extras
Website     : https://www.gnu.org/software/emacs
License     : GPL-3.0-or-later
Updated at  : 31.07.2023 12:57:50
Updated by  : HUMORCE
Installed   : 29.1
Binaries    : bin\runemacs.exe | bin\emacs.exe | bin\emacsclientw.exe | bin\etags.exe | bin\ctags.exe
Shortcuts   : Emacs | Emacs Client
Notes       : For 32-bit version, install 'versions/emacs27.2'
```

## How to reproduce
1. Open org-timeblock with `M-x org-timeblock`
2. Save schedule to file `M-x org-timeblock-write`

### Result
Exported schedule image has empty background.
![image](https://github.com/ichernyshovvv/org-timeblock/assets/87656471/b83322c3-24bd-43b4-86e4-cdb514891f89)

### Expected behavior
Exported schedule image has the same background as current emacs theme.
Image from expected behavior recreated with help of inkscape.
![image](https://github.com/ichernyshovvv/org-timeblock/assets/87656471/a8351075-4ac8-4486-9021-4db3aad05e4d)

P.S.: Thank you for your work on this package.

**Comment by ichernyshovvv** [comment]
Hi. Fixed with https://github.com/ichernyshovvv/org-timeblock/commit/0729f6441d6c052bf1d25b3454ace624680ef80f. Please check if it works for you.

**Comment by artsi0m** [comment]
Thanks a lot, it works for me.
![29_Sep_01_Oct](https://github.com/ichernyshovvv/org-timeblock/assets/87656471/4ebd9c97-65fa-4b0a-b9a5-bf6790ca5c92)

BTW: This BSUIR schedule was converted from icalendar to org format using this script:
https://github.com/ical2org-py/ical2org.py
