### ISSUE TITLE
a question about dependencies

### ISSUE THREAD

**Issue by KonstantinDjairo** [ichernyshovvv/org-timeblock#25]
hi, thank you for this nice software!
i tried install it manually by just using the elisp file, but it didnt go well, but when i tried the straight.el approach it worked like a charm.
it seems that straight just take care of the dependencies automatically, and i wonder if it can be done fully manually

**Comment by ichernyshovvv** [comment]
Hi
> and i wonder if it can be done fully manually
Downloading and installing all the required dependencies for a package is the main feature of package managers (package.el / straight.el / elpaca / etc). Of course you could install everything manually by checking requirements for the package, but I see no point in doing that, except that you just want to waste your time

**Comment by KonstantinDjairo** [comment]
mostly for software preservation.
