### ISSUE TITLE
Wrong type argument

### ISSUE THREAD

**Issue by pierceglenn12345** [ichernyshovvv/org-timeblock#30]
I initially tried to install with:

M-x package-vc-install https://github.com/ichernyshovvv/org-timeblock/

but was getting a Maximum buffer size exceeded error. I ended up just M-x eshell'ing into a file location, git cloning the directory & package-install-file. That seemed to work okay. 

When I ran M-x org-timeblock, it seemed to work the first time. Then when I tried to run again later on, I get the following error message:

org-timeblock: Wrong type argument: stringp, #s(ts nil nil nil nil 9 2023 nil nil nil ...)

Not sure what this is about at the moment. 

Edit: Just set my org-agenda-files to a different location without any .org files to see if there was something wrong with the input, but I get the same error.

**Comment by ichernyshovvv** [comment]
`M-x toggle-debug-on-error` and give me the backtrace buffer when you get this error again.

**Comment by pierceglenn12345** [comment]
After toggling debug on error, I am getting the following when I run M-x org-timeblock:

Debugger entered--Lisp error: (wrong-type-argument stringp #s(ts :hour nil :minute nil :second nil :day nil :month nil :year nil :dow nil :day-abbr nil :day-name nil :doy nil :woy nil :month-abbr nil :month-name nil :tz-abbr nil :tz-offset nil :internal nil :unix 1695071683.1041608))
  org-timeblock-redraw-buffers()
  org-timeblock()
  funcall-interactively(org-timeblock)
  command-execute(org-timeblock record)
  execute-extended-command(nil "org-timeblock" nil)
  funcall-interactively(execute-extended-command nil "org-timeblock" nil)
  command-execute(execute-extended-command)

M-x emacs-version:
GNU Emacs 30.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.20, cairo version 1.16.0) of 2023-09-15

**Comment by ichernyshovvv** [comment]
> but was getting a Maximum buffer size exceeded error

You are the second person reporting this issue here, seems like a bug in package-vc-install. Please `M-x report-emacs-bug`.

> Debugger entered--Lisp error: (wrong-type-argument stringp #s(ts :hour nil :minute nil :second nil :day nil :month nil :year

Do you have this error on Emacs 29.1 release? Would be awesome if you switch to 29.1, because Emacs 30 is in early development, and emacs package developers often get bug reports that even not related to their packages. Also, read this https://www.reddit.com/r/emacs/comments/16dzyma/why_you_shouldnt_use_emacs_30050/

**Comment by pierceglenn12345** [comment]
This is embarrassing. I've never had a break before on bleeding edge, but message received. Thanks for the heads up! 

It works just fine on 29.1

**Comment by pierceglenn12345** [comment]
This is embarrassing. I've never had a break before on bleeding edge, but message received. Thanks for the heads up! 

It works just fine on 29.1
