### ISSUE TITLE
Apperance: background is white with dark themes

### ISSUE THREAD

**Issue by mskorzhinskiy** [ichernyshovvv/org-timeblock#31]
Possibly I have not found the correct way to configure the appearance, but when I try to use this package with `modus-vivendi` theme (i.e. dark background themes), package draws background in white:

![Screenshot from 2023-09-19 22-12-19](https://github.com/ichernyshovvv/org-timeblock/assets/15213728/c8059b53-a97d-4a64-b6cb-674682ed30ec)

Configuration:
- emacs 29.1 from opensuse tumbleweed
- doom emacs 
- a lot of personal customization
- used version of org-timeblock:  43239ca2928ef7ae1e92a968163eed66aaefd459

**Comment by mskorzhinskiy** [comment]
OK. Just took a look into the code:
```
(defvar ot-background-color (face-attribute 'default :background))
```

And for some reason it is `#000000`! I will investigate further.

**Comment by mskorzhinskiy** [comment]
I see now that the implementation tries to determine correct theme background and it seems that it correctly determines that background is pitch-black. However, for some reason, the background is still white and my debugging session didn't yet yield any interesting results.

**Comment by ichernyshovvv** [comment]
The displayed SVG image in `*org-timeblock*` buffer does not have any background. It's transparent =). Do you have this issue with `emacs -q`?

**Comment by mskorzhinskiy** [comment]
> The displayed SVG image in *org-timeblock* buffer does not have any background. It's transparent =).

I see.

> Do you have this issue with emacs -q?

Have not yet tried, but seems to be working fine on my other emacs installation. It is either my emacs configuration issue or emacs installation issue.

I will close the issue, as seems clear that it is not the package issue and will post my findings if I will be able to understand what was wrong for the record.
