### ISSUE TITLE
compat-version error 

### ISSUE THREAD

**Issue by KonstantinDjairo** [ichernyshovvv/org-timeblock#32]
when i try to call org-timeblock :

![image](https://github.com/ichernyshovvv/org-timeblock/assets/53496273/0284163a-ac23-411b-a67b-04695bb29174)

my current config for org-timeblock
![image](https://github.com/ichernyshovvv/org-timeblock/assets/53496273/b5872994-98b6-4bfa-8843-41247a356d58)

i'm using emacs from git, maybe this is why it's not compatible, is there anything that i can do about it?

**Comment by ichernyshovvv** [comment]
Too little information. Did you try it on Emacs 29.1 release? Do you still have the issue?

**Comment by KonstantinDjairo** [comment]
i downgraded to the 29.1, i was using emacs straight from the master, now it works.
