### ISSUE TITLE
Allow control of shown hours

### ISSUE THREAD

**Issue by swflint** [ichernyshovvv/org-timeblock#33]
Would it be possible to set the minimum displayed hour and maximum displayed hour?

**Comment by ichernyshovvv** [comment]
I don't really understand what do you mean. Can you please elaborate?

**Comment by swflint** [comment]
Certainly!  Sorry, I was only half-awake when I wrote this initially.

Is there a way to say, clamp the display to only the hours 8:00 to 18:00?

**Comment by ichernyshovvv** [comment]
There's no such command, but you can call `M-x org-timeblock-switch-scaling` which suddenly stopped working :D. I'll fix that as soon as I have free time

**Comment by swflint** [comment]
Okay, that makes sense.  It's partially what I'm interested in.  I guess, what I'd be more interested in is something like being able to set `org-timeblock-view-options` to something like `(6 . 19)`, and have only the hours 6 to 19 shown.

I may try to PR this shortly.

**Comment by ichernyshovvv** [comment]
Hi, I added the feature, you can now test it. Press `v v` and enter the hours range

**Comment by swflint** [comment]
That seems to work, though there seems to be a regression in that `org-timeblock` shows more days than I've specified in `org-timeblock-n-days-view`.
