### ISSUE TITLE
Cannot show only one day when `org-timeblock-n-days-view` is set to 1

### ISSUE THREAD

**Issue by swflint** [ichernyshovvv/org-timeblock#37]
It appears that it needs to be set to 0 to show only one day.  This is contrary to the docstring.

**Comment by ichernyshovvv** [comment]
Fixed with https://github.com/ichernyshovvv/org-timeblock/commit/f840da6c6722cecc16e8d24a0c500be89f830fd4

**Comment by swflint** [comment]
That works!  Thanks!
