### ISSUE TITLE
Support faces in `org-timeblock-tag-colors`

### ISSUE THREAD

**Issue by protesilaos** [ichernyshovvv/org-timeblock#40]
Hello @ichernyshovvv,

Looking at the `org-timeblock-tag-colors`, I wonder if you have thought about the following approach:

1. Define faces directly, such as to cover the six main colours: red, green, blue, yellow, magenta, cyan. These faces can then be styled by themes to give them the right values.

2. In `org-timeblock-tag-colors` accept a face as an argument, so the user can set something like `("tag" org-timeblock-red)`. The current style can still be accepted as an option (or some variant of it).

The reason I mention these is because right now it is not as easy to switch from a light to a dark theme: the `org-timeblock-tag-colors` needs to be evaluated again with colours that suit the current theme.

**Comment by Aneeqasif** [comment]
yes i guess this would make it look a bit better on various themes 
![Screenshot_20240117_202658](https://github.com/ichernyshovvv/org-timeblock/assets/78728701/b3136b17-6098-4479-877f-8a429644f8d5)

**Comment by ichernyshovvv** [comment]
Hello @protesilaos

> 1. Define faces directly, such as to cover the six main colours: red, green, blue, yellow, magenta, cyan. These faces can then be styled by themes to give them the right values.

I've defined the color faces [here](https://github.com/ichernyshovvv/org-timeblock/commit/39a770e5db211f04a836bbb2f5dc4bb59df2d063) (thanks for the colors, I hope you don't mind, haha. I've put the comment mentioning you right above the faces) and also some additional ones:
- org-timeblock-mark (marked block)
- org-timeblock-hours-line
- org-timeblock-select (selected block)

> 2. In org-timeblock-tag-colors accept a face as an argument, so the user can set something like ("tag" org-timeblock-red). The current style can still be accepted as an option (or some variant of it).

the package now only accepts faces in org-timeblock-tag-colors [commit](https://github.com/ichernyshovvv/org-timeblock/commit/7015685f3c6617331a4b0b63cb534bd2d0b76ace)

Thank you
