### ISSUE TITLE
Time/date range not correctly rendered

### ISSUE THREAD

**Issue by Eejain** [ichernyshovvv/org-timeblock#49]
Thank you very much for making the time blocking in org-agenda an ease! 

I wonder whether the following issue can be easily fixed with certain configurations:

The following heading with the timestamp range format
```
** end of week
   <2024-02-11 Sun 19:40>--<2024-02-11 Sun 20:30>
```
will be rendered as two events in the org-timeblock buffer: one with the correct range, then another one with the second time stamp (see screenshot).

![Screenshot of Emacs at 11_ Feb 2024 at 19_54_50](https://github.com/ichernyshovvv/org-timeblock/assets/5983912/9ae01b24-d6ca-40af-9ce4-c61219d7832b)

Any information will be appreciated!

**Comment by ichernyshovvv** [comment]
Hi, thanks for the report, this is fixed now in the latest [commit](https://github.com/ichernyshovvv/org-timeblock/commit/b423b01712b9c25dff3e4203c7cde736225f62ef)

**Comment by Eejain** [comment]
Hi Ilya, thank you so much for quickly looking into the matter! Although I can't seem to be able to pull the new commit (even with the straight recipe from the repository readme, perhaps it's due to doom emacs's config), I've made local changes in org-timeblock.el `(while (re-search-forward org-tsr-regexp nil t) ` according to the commit. Unfortunately, the same issue has persisted...

**Comment by ichernyshovvv** [comment]
MELPA version has the latest commit version, why not install from it?

If you've changed the source code, you have to byte-recompile the changed file (M-x byte-recompile).

**Comment by Eejain** [comment]
Thank you so much Ilya, both tips are relevant and I installed the new commit from MELPA and the issue was solved!
