### ISSUE TITLE
design: utilize ts.el

### ISSUE THREAD

**Issue by progfolio** [ichernyshovvv/org-timeblock#5]
Your package requires org-ql, which transitively requires ts.el:

https://github.com/alphapapa/org-ql/blob/eb5377320fcfd38354d6e9e3e655969ae3c0e052/org-ql.el#L8

https://github.com/alphapapa/ts.el

You should be able to simplify your library by relying on ts.el's functionality.
e.g. `ot--timestamp-encode` is probably already covered by `ts-parse-org` or `ts-parse-org-element`.

**Comment by ichernyshovvv** [comment]
Hi! Thanks for your contribution. I updated the code, see https://github.com/ichernyshovvv/org-timeblock/commit/0a8ce0f3514fa2f85c460da363a90fed098ea97d
