### ISSUE TITLE
Don't rely on other package's private symbols

### ISSUE THREAD

**Issue by progfolio** [ichernyshovvv/org-timeblock#7]
The following private symbols are referenced directly:

```
svg--append
svg--encode-text
org-fold-core--isearch-reveal 
```

These are not meant to be consumed directly. Their API may change at any time.

**Comment by ichernyshovvv** [comment]
Fixed in https://github.com/ichernyshovvv/org-timeblock/commit/fdb0418d6fe3fcdd1f2004bf02541f129e7c0c81, https://github.com/ichernyshovvv/org-timeblock/commit/2868cbeaa3ba55e9d259c26a09c3105d9bc9d394
