### ISSUE TITLE
Path with org-headlines in the mini-buffer when an agenda item is highlighted

### ISSUE THREAD

**Issue by balaramadurai** [ichernyshovvv/org-timeblock#8]
Hi @ichernyshovvv, 
  This is an excellent package and I love it. I had been using org-gcal to sync my TODOs from org-mode so that I can see how I balance my workload in a visual format.

Your package makes that step unnecessary! 

A suggestion I have is - When I move my focus around, the agenda item highlighted, if it can show the path of the selected item in the mini-buffer, just like how org-agenda does it, that will be great! (Right now, it says `Type C-c C-c to view the image as text`

Thanks again and have a great day!
Bala

**Comment by ichernyshovvv** [comment]
Hi! Thanks for the kind words.

I see no point in that feature. Did you know that you can press `TAB` to jump to the heading of the selected entry?

Though, the message `Type C-c C-c to view the image as text` should be suppressed. Thanks.

**Comment by balaramadurai** [comment]
Hi @ichernyshovvv,
  I agree with you that it may not be a deal-breaker. 

However, in my agenda, I usually have "TODO Write report" for different projects and I tend to club them into a time slot. At that time, I really like the fact that I can see what this is before I jump to this task. And yes, I do know about the `TAB`. 

Thanks
Bala

**Comment by ichernyshovvv** [comment]
Hm, I guess that makes sense sometimes, thanks for the explanation. I'll try to add a customizable variable for that.

**Comment by ichernyshovvv** [comment]
Check the last commit. I added a new defcustom `org-timeblock-show-outline-path` which is nil by default. Does it work fine for you?

**Comment by balaramadurai** [comment]
Yes, perfect. This works.

Thank you for your work.
